version: '3'
services:
  api-server:
    build: .
    tty: true
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: mysql:8.0
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/db/mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
